version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default-network
  app:
    depends_on:
      - postgresdb
    build:
        context: ../home-finders-be
        dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    networks:
      - default-network
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_DOCKER_PORT

volumes: 
  db_data:
networks:
  default-network:
